version: "3.5"
services:
  spalhejs:
    restart: always
    build: .
    ports:
      - "${PORT}:${PORT}"
    command: yarn inititalize
    depends_on:
      - db
    volumes:
      - .:/usr/spalhejs

  db:
    image: mysql:5.6
    restart: always
    environment:
      MYSQL_USER: ${DB_USER}
      MYSQL_ROOT_USER: ${DB_USER}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
    ports:
      - "${DB_PORT}:3306"
